apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds-service
  namespace: devolpment
spec:
  selector:
    matchLabels:
      app: rds-service
  replicas: 1
  template:
    metadata:
      labels:
        app: rds-service
    spec:
      containers:
      - name: rds-service
        image: navedamanat/rds-service:v4

        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8383

---

apiVersion: v1
kind: Service
metadata:
  name: rds-service
  namespace: devolpment
spec:
  selector:
    app: rds-service
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8383
